apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/t8z1b8a3/pretia_repo:63e9af2d5ebf972a51bfbc4755546f536da18519 #ECR here
          resources:
            requests:
              memory: "200M"
              cpu: "100m"
            limits:
              memory: "200M"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /version
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
