name: 'Build and push docker'
on:
  workflow_dispatch:
  push:
  pull_request: 
    types: [closed]
    branches:
      - main

concurrency:
  group: testbuild-group
  cancel-in-progress: true
jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: write
    env: 
      REPO_NAME: "testi"
      REPO_USER: "Bungalo"
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Identify for github
        run:  git config --global user.email "example@exmple123.com"; git config --global user.name "user";
      - name: Clone
        run:  git clone https://github.com/$REPO_USER/$REPO_NAME
        #Using marketplace action for AWS authentication
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::270903434671:role/github_actions
          aws-region: us-east-1
      - name: Authenticate with ECR and push image
        run:  |  
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
            cd $REPO_NAME; docker build -t public.ecr.aws/t8z1b8a3/pretia_repo:$GITHUB_SHA -f deployment/Dockerfile .
            docker image ls
            docker push public.ecr.aws/t8z1b8a3/pretia_repo:$GITHUB_SHA
      
      - name: Update and push feature.yaml
        run:  |
          cd $REPO_NAME; yq -i '(.spec.template.spec.containers[] | select(.name == "nginx") | .image) = "'public.ecr.aws/t8z1b8a3/pretia_repo:$GITHUB_SHA'"' deployment/feature.yaml
          cat deployment/feature.yaml
          git add deployment/feature.yaml
          git commit -m "Update image tag"
          #This push needs to use ssh/other non-repo dependent authentication
          git push https://Bungalo:${{ secrets.GITHUB_TOKEN }}@github.com/$REPO_USER/$REPO_NAME.git      
      - name: check file
        run:  cat testi/deployment/feature.yaml
