name: 'Build and push docker'
on:
  workflow_dispatch:
  push:
  pull_request: 
    types: [closed]
    branches:
      - main

concurrency:
  group: testbuild-group
  cancel-in-progress: true
jobs:
  build-and-push:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Identify for github
        run:  git config --global user.email "tosting@tosting123.com"; git config --global user.name "Bungalo";
      - name: Clone
        run:  git clone https://github.com/Bungalo/testi.git
      - name: Build docker image
        run:  cd testi; docker build -t joonatan:$GITHUB_SHA -f deployment/Dockerfile .
      - name: check image
        run:  docker image ls
      
      - name: Authenticate with ECR and push image
        env:  
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run:  |  
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
            docker push public.ecr.aws/t8z1b8a3/joonatan
      
      - name: Update feature.yaml
        run:  cd testi; yq -i '(.spec.template.spec.containers[] | select(.name == "nginx") | .image) = "'joonatan:$GITHUB_SHA'"' deployment/feature.yaml
      - name: check file
        run:  cat testi/deployment/feature.yaml
      - name: Push updated file
        run:  cd testi; git add deployment/feature.yaml; git commit -m "Update image tag"; git push https://Bungalo:${{ secrets.REPOTOKEN }}@github.com/Bungalo/testi.git
