name: 'Run tests and build image'
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: testbuild-group
  cancel-in-progress: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checKout
        uses: actions/checkout@v4
      - name: Make script executable
        run:  chmod +x script.sh
      - name: hello
        run: ./script.sh
