name: 'Run tests and build image'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: testbuild-group
  cancel-in-progress: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkkiaut
        run:  git clone https://github.com/Bungalo/testi.git ; cd testi ; git checkout $GITHUB_HEAD_REF; git branch
      - name: Make script executable
        run:  chmod +x testi/script.sh
      - name: hello
        run: testi/script.sh
#as
