name: 'Run tests and build image'
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: testbuild-group
  cancel-in-progress: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
  steps:
    uses: actions/checkout@v4
