name: 'Release tag'
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
concurrency:
  group: releasebuild-group
  cancel-in-progress: true
jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: write
    env: 
      REPO_NAME:  "testi"
      REPO_USER:  "Bungalo"
      USERNAME:   "Bungalo"
    runs-on: ubuntu-latest
    steps:
      - name: Identify for github
        run:  git config --global user.email "example@exmple123.com"; git config --global user.name "user";
      - name: Clone
        run:  git clone https://github.com/$REPO_USER/$REPO_NAME
        #Using marketplace action for AWS authentication
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::270903434671:role/github_actions
          aws-region: us-east-1
      - name: Authenticate with ECR and push image
        run:  | 
          echo $GITHUB_REF_NAME 
          gh release create $GITHUB_REF_NAME --generate-notes
